# Generated by Django 2.1.3 on 2018-12-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tco_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('iso_code', models.CharField(max_length=10)),
                ('locale_code', models.CharField(max_length=50)),
            ],
        ),
    ]
